-- CREATE QUESTION_SUBJECT TYPE
DROP TYPE IF EXISTS QUESTION_SUBJECT;
CREATE TYPE QUESTION_SUBJECT AS ENUM (
    'PHYSICS',
    'CHEMISTRY',
    'GEOGRAPHY',
    'BIOLOGY',
    'HISTORY',
    'LITERATURE',
    'POP_CULTURE',
    'INFORMATION_TECHNOLOGY'
);

-- CREATE OPTIONS TABLE
DROP TABLE IF EXISTS OPTIONS;
CREATE TABLE OPTIONS (
    ID SERIAL PRIMARY KEY,
    OPTION_TEXT VARCHAR NOT NULL,
    QUESTION_ID SMALLINT
);

-- CREATE QUESTIONS TABLE
DROP TABLE IF EXISTS QUESTIONS;
CREATE TABLE QUESTIONS (
    ID SERIAL PRIMARY KEY,
    QUESTION_TEXT VARCHAR NOT NULL,
    QUESTION_SUBJECT QUESTION_SUBJECT,
    CORRECT_OPTION_ID SMALLINT
);

-- INITIALISE OPTIONS TABLE WITH DATA
INSERT INTO OPTIONS(ID, OPTION_TEXT, QUESTION_ID)
VALUES
    (1, 'Marrakesh', 22),
    (2, 'Canada', 5),
    (3, 'What is the capital city of Norway?', 1997),
    (4, 'What is the capital city of Norway?', 1997),
    (5, 'What is the capital city of Norway?', 1997),
    (6, 'What is the capital city of Norway?', 1997),
    (7, 'What is the capital city of Norway?', 1997),
    (8, 'What is the capital city of Norway?', 1997),
    (9, 'What is the capital city of Norway?', 1997),
    (10, 'What is the capital city of Norway?', 1997),
    (11, 'What is the capital city of Norway?', 1997),
    (12, 'Oslo', 1),
    (13, 'What is the capital city of Norway?', 1997),
    (14, 'What is the capital city of Norway?', 1997),
    (15, 'Antonio Banderas', 7),
    (16, 'What is the capital city of Norway?', 1997),
    (17, 'What is the capital city of Norway?', 1997),
    (18, 'Brazil', 5),
    (19, 'What is the capital city of Norway?', 1997),
    (20, 'What is the capital city of Norway?', 1997),
    (21, 'What is the capital city of Norway?', 1997),
    (22, 'What is the capital city of Norway?', 1997),
    (23, 'What is the capital city of Norway?', 1997),
    (24, 'What is the capital city of Norway?', 1997),
    (25, 'Casablanca', 22),
    (26, '1899', 4),
    (27, 'What is the capital city of Norway?', 1997),
    (28, 'What is the capital city of Norway?', 1997),
    (29, 'What is the capital city of Norway?', 1997),
    (30, 'What is the capital city of Norway?', 1997),
    (31, 'China', 5),
    (32, 'What is the capital city of Norway?', 1997),
    (33, 'What is the capital city of Norway?', 1997),
    (34, 'What is the capital city of Norway?', 1997),
    (35, 'What is the capital city of Norway?', 1997),
    (36, 'Bergen', 1),
    (37, 'What is the capital city of Norway?', 1997),
    (38, 'What is the capital city of Norway?', 1997),
    (39, 'xenon', 3),
    (40, 'What is the capital city of Norway?', 1997),
    (41, 'What is the capital city of Norway?', 1997),
    (42, 'What is the capital city of Norway?', 1997),
    (43, 'Tommy Lee Jones', 7),
    (44, 'What is the capital city of Norway?', 1997),
    (45, 'What is the capital city of Norway?', 1997),
    (46, 'What is the capital city of Norway?', 1997),
    (47, 'India', 5),
    (48, 'What is the capital city of Norway?', 1997),
    (49, 'What is the capital city of Norway?', 1997),
    (50, 'What is the capital city of Norway?', 1997),
    (51, 'argon', 3),
    (52, 'What is the capital city of Norway?', 1997),
    (53, 'What is the capital city of Norway?', 1997),
    (54, 'oxygen', 3),
    (55, '1912', 4),
    (56, 'Williams Syndrome', 6),
    (57, 'What is the capital city of Norway?', 1997),
    (58, 'Denzel Washington', 7),
    (59, 'What is the capital city of Norway?', 1997),
    (60, 'What is the capital city of Norway?', 1997),
    (61, 'What is the capital city of Norway?', 1997),
    (62, 'What is the capital city of Norway?', 1997),
    (63, 'Tangier', 22),
    (64, 'What is the capital city of Norway?', 1997),
    (65, 'What is the capital city of Norway?', 1997),
    (66, 'What is the capital city of Norway?', 1997),
    (67, 'What is the capital city of Norway?', 1997),
    (68, 'deployment', 2),
    (69, 'What is the capital city of Norway?', 1997),
    (70, 'What is the capital city of Norway?', 1997),
    (71, 'What is the capital city of Norway?', 1997),
    (72, 'What is the capital city of Norway?', 1997),
    (73, '1961', 4),
    (74, 'What is the capital city of Norway?', 1997),
    (75, 'What is the capital city of Norway?', 1997),
    (76, 'What is the capital city of Norway?', 1997),
    (77, 'Tom Hanks', 7),
    (78, 'What is the capital city of Norway?', 1997),
    (79, 'What is the capital city of Norway?', 1997),
    (80, 'What is the capital city of Norway?', 1997),
    (81, 'What is the capital city of Norway?', 1997),
    (82, 'Molde', 1),
    (83, 'What is the capital city of Norway?', 1997),
    (84, 'What is the capital city of Norway?', 1997),
    (85, 'What is the capital city of Norway?', 1997),
    (86, 'statefulset', 2),
    (87, 'What is the capital city of Norway?', 1997),
    (88, 'What is the capital city of Norway?', 1997),
    (89, 'What is the capital city of Norway?', 1997),
    (90, 'Reye Syndrome', 6),
    (91, 'What is the capital city of Norway?', 1997),
    (92, 'What is the capital city of Norway?', 1997),
    (93, 'What is the capital city of Norway?', 1997),
    (94, 'What is the capital city of Norway?', 1997),
    (95, 'Rabat', 22),
    (96, 'What is the capital city of Norway?', 1997),
    (97, 'What is the capital city of Norway?', 1997),
    (98, 'What is the capital city of Norway?', 1997),
    (99, 'What is the capital city of Norway?', 1997),
    (100, 'What is the capital city of Norway?', 1997),
    (101, 'What is the capital city of Norway?', 1997),
    (102, 'What is the capital city of Norway?', 1997),
    (103, 'daemonset', 2),
    (104, 'What is the capital city of Norway?', 1997),
    (105, 'What is the capital city of Norway?', 1997),
    (106, 'What is the capital city of Norway?', 1997),
    (107, 'What is the capital city of Norway?', 1997),
    (108, 'What is the capital city of Norway?', 1997),
    (109, 'Crohn''s Disease', 6),
    (110, 'What is the capital city of Norway?', 1997),
    (111, 'What is the capital city of Norway?', 1997),
    (112, 'What is the capital city of Norway?', 1997),
    (113, 'What is the capital city of Norway?', 1997),
    (114, '1910', 4),
    (115, 'krypton', 3),
    (116, 'Harstad', 1),
    (117, 'What is the capital city of Norway?', 1997),
    (118, 'What is the capital city of Norway?', 1997),
    (119, 'Wilson Disease', 6),
    (120, 'replicaset', 2);

-- INITIALISE QUESTIONS TABLE WITH DATA
INSERT INTO QUESTIONS(ID, QUESTION_TEXT, QUESTION_SUBJECT, CORRECT_OPTION_ID)
VALUES
    (1, 'What is the capital city of Norway?', 'GEOGRAPHY', 12),
    (2, 'Which Kubernetes resource allows for exactly a single instance of a pod to run on every node within the cluster?', 'INFORMATION_TECHNOLOGY', 103),
    (3, 'Which one of the following elements is NOT a noble gas?', 'CHEMISTRY', 54),
    (4, 'In which year did the Union of South Africa come into existence?', 'HISTORY', 114),
    (5, 'Which is the second largest country in the world (by area)?', 'GEOGRAPHY', 2),
    (6, 'Which rare disorder causes an unusually high amount of copper to accumulate in the human body, particularly inside the liver?', 'BIOLOGY', 119),
    (7, 'Which actor won the 1994 Academy Award for Best Actor for his role in the film "Philadelphia"?', 'POP_CULTURE', 77),
    (8, 'What is the capital city of Norway?', 'Geography', 1997),
    (9, 'What is the capital city of Norway?', 'Geography', 1997),
    (10, 'What is the capital city of Norway?', 'Geography', 1997),
    (11, 'What is the capital city of Norway?', 'Geography', 1997),
    (12, 'What is the capital city of Norway?', 'Geography', 1997),
    (13, 'What is the capital city of Norway?', 'Geography', 1997),
    (14, 'What is the capital city of Norway?', 'Geography', 1997),
    (15, 'What is the capital city of Norway?', 'Geography', 1997),
    (16, 'What is the capital city of Norway?', 'Geography', 1997),
    (17, 'What is the capital city of Norway?', 'Geography', 1997),
    (18, 'What is the capital city of Norway?', 'Geography', 1997),
    (19, 'What is the capital city of Norway?', 'Geography', 1997),
    (20, 'What is the capital city of Norway?', 'Geography', 1997),
    (21, 'What is the capital city of Norway?', 'Geography', 1997),
    (22, 'What is the capital city of Morocco?', 'GEOGRAPHY', 95),
    (23, 'What is the capital city of Norway?', 'Geography', 1997),
    (24, 'What is the capital city of Norway?', 'Geography', 1997),
    (25, 'What is the capital city of Norway?', 'Geography', 1997),
    (26, 'What is the capital city of Norway?', 'Geography', 1997),
    (27, 'What is the capital city of Norway?', 'Geography', 1997),
    (28, 'What is the capital city of Norway?', 'Geography', 1997),
    (29, 'What is the capital city of Norway?', 'Geography', 1997),
    (30, 'What is the capital city of Norway?', 'Geography', 1997);